### ISSUE TITLE
Don´t work for me

### ISSUE THREAD

**Issue by Bur2** [maxssestepa/Latchwake#1]
Hi, first thanks for sharing this, I need something like this. I install following the instructions in my Raspberry Pi, but it don´t work for me. I avtivated the option to run service in boot, reboot my Raspberry connected to my router with etherenet and try to boot my pc, also connected in the same way to the same router. It don´t work for me, I only get to Latch notify me if I have off and the pc is on. 
I need some information about how this works or what requirements. Thanks and sorry for my bad English.

**Comment by ManuSecEs** [comment]
Hablo español también, si lo prefieres.
The program should go well. It is well tested.
**You must activate Wake-On-Lan in the BIOS/UEFI of computers to run.**
Sent a more detailed manual for you to understand.

https://drive.google.com/file/d/0B1VM3nUrISLZZE9MVmEzVUFPdHM/view?usp=sharing
